[core]
reloadable = true
order = 0

[package]
version = "0.4.0"
category = "Simulation"
title = "Asimov Jaka Minicobo Robot"
description = "Asimov Jaka Minicobo Robot Helper Class"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.manipulators" = {}

[[python.module]]
name = "omni.asimov.jaka"
